"""The wall between simulated data and model training.

Every frame that flows through this pipeline declares its origin. Training refuses
anything that did not come from a measured source.

This exists because the failure it prevents is silent and fatal. If simulator output
reached `train.py`, the model would learn the generative rules written in
`simulate.py` -- it would score well, and every metric in the evaluation chapter would
be measuring nothing but the simulator's own assumptions reflected back. There would be
no error, no warning, and no way to tell from the numbers that it had happened.

So origin is a column, not a convention:

    from provenance import mark_synthetic, mark_measured, assert_measured

    demo = mark_synthetic(generated_frame)      # simulator output
    real = mark_measured(lifesnaps_frame)       # ingested from a dataset
    assert_measured(training_frame)             # raises if anything synthetic slipped in

See docs/DATASET.md section 6.
"""

from __future__ import annotations

import pandas as pd

#: Column carrying each row's origin. Present on every frame in the pipeline.
ORIGIN_COLUMN = "data_origin"

#: Rows generated by ml/simulate.py. Valid for demos, fixtures and task_density.
SYNTHETIC = "synthetic"

#: Rows ingested from a public research dataset. The only origin training accepts.
MEASURED = "measured"


class SyntheticDataInTrainingError(RuntimeError):
    """Raised when simulated rows reach a stage that must only see measured data."""


def mark_synthetic(frame: pd.DataFrame) -> pd.DataFrame:
    """Tag every row as simulator output. Call this in `simulate.py`, nowhere else."""
    tagged = frame.copy()
    tagged[ORIGIN_COLUMN] = SYNTHETIC
    return tagged


def mark_measured(frame: pd.DataFrame, source: str) -> pd.DataFrame:
    """Tag every row as ingested from `source` (e.g. "lifesnaps"). Call this in ingest_*.py."""
    tagged = frame.copy()
    tagged[ORIGIN_COLUMN] = MEASURED
    tagged["source_dataset"] = source
    return tagged


def assert_measured(frame: pd.DataFrame, stage: str = "training") -> None:
    """Refuse to proceed unless every row is measured.

    An untagged frame is treated as a failure rather than assumed clean: a missing
    origin column means some path built a frame without declaring where it came from,
    which is exactly the situation this guard exists to catch.
    """
    if ORIGIN_COLUMN not in frame.columns:
        raise SyntheticDataInTrainingError(
            f"{stage}: frame has no '{ORIGIN_COLUMN}' column, so its origin cannot be "
            f"established. Tag it with provenance.mark_measured() at ingest."
        )

    origins = set(frame[ORIGIN_COLUMN].unique())
    disallowed = origins - {MEASURED}
    if disallowed:
        counts = frame[ORIGIN_COLUMN].value_counts().to_dict()
        raise SyntheticDataInTrainingError(
            f"{stage}: refusing to proceed -- frame contains non-measured rows "
            f"{sorted(disallowed)}. Row counts by origin: {counts}. "
            f"Simulated data must never be trained on (docs/DATASET.md section 6)."
        )


def is_synthetic(frame: pd.DataFrame) -> bool:
    """True if any row came from the simulator."""
    return ORIGIN_COLUMN in frame.columns and (frame[ORIGIN_COLUMN] == SYNTHETIC).any()
