<?php

namespace App\Console\Commands;

use App\Domain\Profile\Repository\UserProfileRepository;
use App\Domain\Wellbeing\ValueObject\UserId;
use App\Models\ExerciseSession;
use App\Models\HealthSnapshot;
use App\Models\MealEntry;
use App\Models\User;
use Illuminate\Console\Command;

/**
 * Writes a seeded account out as the request bodies that would recreate it.
 *
 * The seeders can only run where there is a shell on the database. The deployed API
 * sits behind a security group that admits SSH from one address, so seeding the
 * demo account there means writing through the public API instead —
 * `tools/seed_demo_via_api.py` does that, and this produces what it sends.
 *
 * Exporting rather than reimplementing keeps one definition of what the demo
 * account holds: run the seeders locally, export, post. A second generator in
 * another language would drift from this one the first time a field moved.
 *
 * Field names here are the API's, not the table's — this is a request body, and
 * `eaten_on` and `performed_on` are absent because both controllers derive the day
 * from the instant the client sent.
 */
class ExportDemoPayload extends Command
{
    protected $signature = 'auraflow:export-demo-payload
        {email : The seeded account to export}
        {--path= : Where to write the JSON (default: ../tools/demo-payload.json)}';

    protected $description = 'Export a seeded demo account as API request bodies';

    public function handle(UserProfileRepository $profiles): int
    {
        $user = User::query()->where('email', $this->argument('email'))->first();

        if (! $user) {
            $this->error('No account found for '.$this->argument('email').'.');

            return self::FAILURE;
        }

        $path = (string) ($this->option('path') ?: base_path('../tools/demo-payload.json'));
        $profile = $profiles->findFor(UserId::fromString((string) $user->id));

        $payload = [
            '_note' => 'Generated by `php artisan auraflow:export-demo-payload`. '
                .'Synthetic demonstration data — not measured, never used for training.',
            'profile' => [
                'date_of_birth' => $profile?->dateOfBirth()?->format('Y-m-d'),
                'sex' => $profile?->sex()->value,
                'height_cm' => $profile?->heightCm(),
                'weight_kg' => $profile?->weightKg(),
                'activity_level' => $profile?->statedActivityLevel()?->value,
            ],
            'snapshots' => HealthSnapshot::query()
                ->where('user_id', $user->id)
                ->orderBy('recorded_on')
                ->get()
                ->map(fn (HealthSnapshot $s): array => [
                    'recorded_on' => $s->recorded_on->format('Y-m-d'),
                    'sleep_minutes' => $s->sleep_minutes,
                    'deep_sleep_minutes' => $s->deep_sleep_minutes,
                    'rem_sleep_minutes' => $s->rem_sleep_minutes,
                    'resting_heart_rate' => $s->resting_heart_rate,
                    'resting_hr_source' => $s->resting_hr_source,
                    'steps' => $s->steps,
                    'steps_are_complete' => (bool) $s->steps_are_complete,
                    'water_ml' => $s->water_ml,
                ])
                ->values()
                ->all(),
            'meals' => MealEntry::query()
                ->where('user_id', $user->id)
                ->orderBy('eaten_at')
                ->get()
                ->map(fn (MealEntry $m): array => [
                    'eaten_at' => $m->eaten_at->format('Y-m-d H:i:s'),
                    'name' => $m->name,
                    'kcal' => $m->kcal,
                    'source' => $m->source,
                    'barcode' => $m->barcode,
                    'protein_g' => $m->protein_g,
                    'carbs_g' => $m->carbs_g,
                    'fat_g' => $m->fat_g,
                    'portion_g' => $m->portion_g,
                ])
                ->values()
                ->all(),
            'sessions' => ExerciseSession::query()
                ->where('user_id', $user->id)
                ->orderBy('performed_at')
                ->get()
                ->map(fn (ExerciseSession $s): array => [
                    'performed_at' => $s->performed_at->format('Y-m-d H:i:s'),
                    'exercise' => $s->exercise,
                    'source' => $s->source,
                    'total_reps' => $s->total_reps,
                    'good_form_reps' => $s->good_form_reps,
                    'duration_seconds' => $s->duration_seconds,
                    'mean_heart_rate' => $s->mean_heart_rate,
                    'prescribed_intensity' => $s->prescribed_intensity,
                    'recovery_score' => $s->recovery_score,
                    'client_uuid' => $s->client_uuid,
                ])
                ->values()
                ->all(),
        ];

        @mkdir(dirname($path), 0o755, true);
        file_put_contents(
            $path,
            json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
        );

        $this->info(sprintf(
            'Wrote %d nights, %d meals and %d sessions to %s',
            count($payload['snapshots']),
            count($payload['meals']),
            count($payload['sessions']),
            $path,
        ));

        return self::SUCCESS;
    }
}
