<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * One generated briefing per user per day.
 *
 * Persisted rather than generated on demand for three reasons: a language model call
 * costs money and latency, the same day's data yields the same advice so regenerating is
 * waste, and a briefing the user already read should not silently reword itself when they
 * reopen the app.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('daily_briefs', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->date('brief_for');

            $table->string('status')->default('pending'); // pending | ready | failed
            $table->text('body')->nullable();

            // Which model wrote it. Advice generated by a model that has since been
            // replaced should be identifiable rather than anonymous.
            $table->string('model')->nullable();
            $table->string('failure_reason')->nullable();
            $table->timestamp('generated_at')->nullable();

            $table->timestamps();

            // One per user per day; the job is queued from a request that may fire twice.
            $table->unique(['user_id', 'brief_for']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('daily_briefs');
    }
};
